### ISSUE TITLE
小米手机拍视频时的Bug

### ISSUE THREAD

**Issue by wangshuaialex** [jxj2118/JCamera#10]
日志信息贴出来，如下：
Mp4Composer: This devicel cannot codec with that setting. Check width, height, bitrate and video format.
    android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2023)
        at android.media.MediaCodec.configure(MediaCodec.java:1951)
        at com.daasuu.mp4compose.composer.VideoComposer.setUp(VideoComposer.java:81)
        at com.daasuu.mp4compose.composer.Mp4ComposerEngine.compose(Mp4ComposerEngine.java:107)
        at com.daasuu.mp4compose.composer.Mp4Composer$2.run(Mp4Composer.java:268)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

 W/System.err: android.media.MediaCodec$CodecException: Error 0xfffffc0e
 W/System.err:     at android.media.MediaCodec.native_configure(Native Method)
 W/System.err:     at android.media.MediaCodec.configure(MediaCodec.java:2023)
 W/System.err:     at android.media.MediaCodec.configure(MediaCodec.java:1951)
 W/System.err:     at com.daasuu.mp4compose.composer.VideoComposer.setUp(VideoComposer.java:81)
 W/System.err:     at com.daasuu.mp4compose.composer.Mp4ComposerEngine.compose(Mp4ComposerEngine.java:107)
 W/System.err:     at com.daasuu.mp4compose.composer.Mp4Composer$2.run(Mp4Composer.java:268)
 W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 W/System.err:     at java.lang.Thread.run(Thread.java:919)

**Comment by wangshuaialex** [comment]
然后我再看下日志， 有段宽高设置的提示：Unsupported Resolution WxH = (1080)x(2400) Supported Range = min (32)x(32) - max (864)x(480)，现在看来是取的拍摄视频宽高超出范围了吗

**Comment by wangshuaialex** [comment]
![image](https://user-images.githubusercontent.com/17693726/178096414-7a8a400d-c682-493e-a180-5d36d8e35251.png)

看来下源码是Mp4Composer里面的对width、height、bitrate或者是video format有问题，JCamera里面有没有入口，可以去操作Mp4Composer里面的内容呢
